$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://github.com/luebken/ccrm/schemas/company.yaml"
title: Company
description: Organizations and businesses
type: object
required:
  - name
  - type
  - owner
  - created_at
  - updated_at
additionalProperties: false

properties:
  hubspot_id:
    type: string
    description: Unique identifier for HubSpot integration

  name:
    type: string
    minLength: 1
    description: Company name

  domain:
    type: string
    format: hostname
    description: Primary domain/website

  industry:
    type: string
    description: Industry sector

  size:
    type: string
    enum:
      - "1-10"
      - "11-50"
      - "51-200"
      - "201-500"
      - "501-1000"
      - "1000+"
    description: Employee count range

  revenue:
    type: string
    description: Annual revenue range

  type:
    type: string
    enum:
      - prospect
      - customer
      - partner
      - vendor
      - other
    description: Company type

  contacts:
    type: array
    items:
      type: string
      pattern: "^\\[\\[contacts/[a-z0-9-]+\\]\\]$"
    description: Array of contact wikilinks

  opportunities:
    type: array
    items:
      type: string
      pattern: "^\\[\\[opportunities/[a-z0-9-]+\\]\\]$"
    description: Array of opportunity wikilinks

  owner:
    type: string
    minLength: 1
    description: Owner name

  phone:
    type: string
    description: Main phone number

  address:
    type: string
    description: Company address

  tags:
    type: array
    items:
      type: string
    description: Array of tags

  created_at:
    type: string
    format: date-time
    description: Creation date

  updated_at:
    type: string
    format: date-time
    description: Last modified date
